<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EnvSync.Providers.Vault\EnvSync.Providers.Vault.csproj" />
    <ProjectReference Include="..\EnvSync.TestSupport\EnvSync.TestSupport.csproj" />
  </ItemGroup>

</Project>
