<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" />
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EnvSync.Cli\EnvSync.Cli.csproj" />
    <ProjectReference Include="..\EnvSync.TestSupport\EnvSync.TestSupport.csproj" />
    <ProjectReference Include="..\EnvSync.TestChild\EnvSync.TestChild.csproj" />
  </ItemGroup>

</Project>
