<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EnvSync.Application\EnvSync.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SecretsManager" />
    <PackageReference Include="AWSSDK.SSO" />
    <PackageReference Include="AWSSDK.SSOOIDC" />
    <PackageReference Include="AWSSDK.SecurityToken" />
  </ItemGroup>

</Project>
